export const STATS = [
  {
    label: "Active Tours",
    value: "24",
    change: "3 new",
    trend: "up",
    sub: "vs 21 last month",
  },
  {
    label: "Total Bookings",
    value: "148",
    change: "12%",
    trend: "up",
    sub: "vs 132 last month",
  },
  {
    label: "Revenue",
    value: "$36k",
    change: "2%",
    trend: "down",
    sub: "vs $37k last month",
  },
  {
    label: "Avg. Rating",
    value: "4.8",
    change: "0.2",
    trend: "up",
    sub: "from 4.6 last month",
  },
];

export const REVENUE_DATA = [
  { month: "Jan", revenue: 18 },
  { month: "Feb", revenue: 22 },
  { month: "Mar", revenue: 19 },
  { month: "Apr", revenue: 28 },
  { month: "May", revenue: 32 },
  { month: "Jun", revenue: 27 },
  { month: "Jul", revenue: 38 },
  { month: "Aug", revenue: 42 },
  { month: "Sep", revenue: 35 },
  { month: "Oct", revenue: 40 },
  { month: "Nov", revenue: 36 },
  { month: "Dec", revenue: 45 },
];

export const BOOKINGS = [
  {
    customer: "Sarah Johnson",
    tour: "Everest Base Camp Trek",
    date: "Dec 10, 2025",
    people: "2",
    amount: "$2,800",
    status: "Confirmed",
    statusVariant: "green" as const,
  },
  {
    customer: "Marco Bianchi",
    tour: "Annapurna Circuit",
    date: "Dec 15, 2025",
    people: "4",
    amount: "$5,200",
    status: "Confirmed",
    statusVariant: "green" as const,
  },
  {
    customer: "Yuki Tanaka",
    tour: "Kathmandu Valley Heritage",
    date: "Dec 20, 2025",
    people: "2",
    amount: "$980",
    status: "Pending",
    statusVariant: "amber" as const,
  },
  {
    customer: "Emma Wilson",
    tour: "Langtang Valley Trek",
    date: "Jan 5, 2026",
    people: "3",
    amount: "$3,600",
    status: "Confirmed",
    statusVariant: "green" as const,
  },
  {
    customer: "Carlos Ruiz",
    tour: "Poon Hill Sunrise Trek",
    date: "Jan 12, 2026",
    people: "2",
    amount: "$1,400",
    status: "Pending",
    statusVariant: "amber" as const,
  },
  {
    customer: "Lena Müller",
    tour: "Everest Base Camp Trek",
    date: "Jan 20, 2026",
    people: "1",
    amount: "$1,400",
    status: "Cancelled",
    statusVariant: "red" as const,
  },
];

export const TOURS = [
  {
    name: "Everest Base Camp Trek",
    location: "Khumbu Region",
    category: "Trekking",
    duration: "14 Days",
    difficulty: "Challenging",
    difficultyVariant: "red" as const,
    price: "From $1,400",
    rating: "4.9",
    status: "Active",
    statusVariant: "green" as const,
  },
  {
    name: "Annapurna Circuit",
    location: "Annapurna Region",
    category: "Trekking",
    duration: "18 Days",
    difficulty: "Moderate",
    difficultyVariant: "amber" as const,
    price: "From $1,200",
    rating: "4.8",
    status: "Active",
    statusVariant: "green" as const,
  },
  {
    name: "Kathmandu Valley Heritage",
    location: "Kathmandu",
    category: "Culture",
    duration: "5 Days",
    difficulty: "Easy",
    difficultyVariant: "green" as const,
    price: "From $499",
    rating: "4.7",
    status: "Active",
    statusVariant: "green" as const,
  },
  {
    name: "Langtang Valley Trek",
    location: "Langtang Region",
    category: "Trekking",
    duration: "10 Days",
    difficulty: "Moderate",
    difficultyVariant: "amber" as const,
    price: "From $900",
    rating: "4.6",
    status: "Active",
    statusVariant: "green" as const,
  },
  {
    name: "Poon Hill Sunrise Trek",
    location: "Ghorepani",
    category: "Adventure",
    duration: "5 Days",
    difficulty: "Easy",
    difficultyVariant: "green" as const,
    price: "From $650",
    rating: "4.8",
    status: "Active",
    statusVariant: "green" as const,
  },
  {
    name: "Mustang Kingdom Trail",
    location: "Upper Mustang",
    category: "Culture",
    duration: "12 Days",
    difficulty: "Moderate",
    difficultyVariant: "amber" as const,
    price: "From $2,200",
    rating: "4.9",
    status: "Draft",
    statusVariant: "gray" as const,
  },
];

export const POPULAR_TOURS = [
  { name: "Everest Base Camp", bookings: 48, revenue: "$67.2k", rating: "4.9" },
  { name: "Annapurna Circuit", bookings: 36, revenue: "$43.2k", rating: "4.8" },
  { name: "Kathmandu Heritage", bookings: 31, revenue: "$15.5k", rating: "4.7" },
  { name: "Poon Hill Sunrise", bookings: 28, revenue: "$18.2k", rating: "4.8" },
  { name: "Langtang Valley", bookings: 19, revenue: "$17.1k", rating: "4.6" },
];

export const CUSTOMERS = [
  { name: "Sarah Johnson", email: "sarah.j@gmail.com", country: "USA", bookings: 3, spent: "$8,400", joined: "Mar 2024" },
  { name: "Marco Bianchi", email: "marco.b@email.it", country: "Italy", bookings: 2, spent: "$5,200", joined: "Jun 2024" },
  { name: "Yuki Tanaka", email: "yuki.t@jp.com", country: "Japan", bookings: 1, spent: "$980", joined: "Sep 2024" },
  { name: "Emma Wilson", email: "emma.w@uk.co", country: "UK", bookings: 4, spent: "$11,600", joined: "Jan 2024" },
  { name: "Carlos Ruiz", email: "c.ruiz@es.com", country: "Spain", bookings: 2, spent: "$3,800", joined: "Aug 2024" },
  { name: "Lena Müller", email: "lena.m@de.com", country: "Germany", bookings: 1, spent: "$1,400", joined: "Nov 2024" },
];

export const REVIEWS = [
  {
    author: "Sarah Johnson",
    tour: "Everest Base Camp Trek",
    date: "Nov 28, 2025",
    rating: 5,
    comment:
      "An absolutely life-changing experience. The guides were incredibly knowledgeable and professional. Standing at Base Camp was a moment I'll treasure forever.",
  },
  {
    author: "Marco Bianchi",
    tour: "Annapurna Circuit",
    date: "Nov 15, 2025",
    rating: 5,
    comment:
      "The Annapurna Circuit is everything they say and more. Perfectly organized, great accommodation stops, and breathtaking scenery every single day.",
  },
  {
    author: "Emma Wilson",
    tour: "Kathmandu Valley Heritage",
    date: "Oct 30, 2025",
    rating: 4,
    comment:
      "Wonderful cultural immersion. Our guide Prakash was exceptional — his knowledge of the temples and history brought everything to life. Would highly recommend.",
  },
];
